/**
 * Initial symptom input from patient
 */
export interface SymptomInput {
	symptoms: string;
	createdAt: string;
}

/**
 * Follow-up questions generated by backend
 */
export interface FollowUpQuestion {
	id: string;
	question: string;
}
